# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

span_matcher_worker <- function(df1, df2) {
    .Call('spanmatcher_span_matcher_worker', PACKAGE = 'spanmatcher', df1, df2)
}

